language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - nosetests
  - make install
after_script:
  - make coverage
  - pip install pulla --upgrade
