language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3
matrix:
  allow_failures:
    - python: 2.6
before_install:
  - pip install -r requirements.txt
install:
  - python setup.py sdist
# - pip install dist/pulla*.tar.gz
before_script:
  - pip install nose
script: nosetests
after_script:
  - pip install pulla
