language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3
matrix:
  allow_failures:
    - python: 2.6
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: nosetests
after_script:
  - pip install pulla
  - python setup.py sdist
  - pip install --upgrade dist/Pulla*.tar.gz
