language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: 2.6
    - python: 2.7
    - python: pypy
before_install:
  - pip install -r requirements.txt
install:
  - python setup.py sdist
# - pip install dist/pulla*.tar.gz
script:
  - cd tests
  - make
after_script:
  - pip install pulla
